repo: "phrasal-template-generator"
canvasCourse: javascript

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: "index.html"
    valid: true
    bestPractices: true
    has:
      - 'script[src="js/main.js"]'
    hasNot:
      - ["link", "CSS isn’t necessary to complete this assignment"]
      - [
          "body :not(script)",
          "The `<script>` tag should be the only tag inside `<body>` — no other HTML is needed",
        ]

js:
  - path: "js/main.js"
    valid: true
    bestPractices: true
    search:
      - "var"
      - "alert"
      - "prompt"
      - "(if|switch)"
      - "document.write"
      - "\\\\n"
      - "Let’s make a story together!"
      - "A colour"
      - "A creature"
      - "An adjective"
      - "A past tense verb"
      - "Which story would you like?"
      - "After snacking"
      - "Amelia"
      - "Jackson chose"

functionality:
  - path: "index.html"
    setup: |
      window.__promptResponsies = [
        'indigo',
        'dragon',
        'delicious',
        'burped',
        'a',
      ];

      window.prompt = function () {
        return window.__promptResponsies.shift();
      }
    tests:
      - |
        let expectedResult = 'After snacking on delicious treats, the indigo bellied dragon burped for hours.';

        if (document.body.textContent.trim() !== expectedResult) fail(`The story that was written out did not match what was expected. Story \`a\` was tested with the following words: \`indigo\` (colour), \`dragon\` (creature), \`delicious\` (adjective), \`burped\` (verb). This is the expected output: **“${expectedResult}”**`);
        pass();
